<?php

namespace AppBundle\Entity;

/**
 * BeitragRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BeitragRepository extends \Doctrine\ORM\EntityRepository
{
}
