<?php

namespace AppBundle\Entity;

/**
 * ProjektRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjektRepository extends \Doctrine\ORM\EntityRepository
{
}
